### ISSUE TITLE
Why UI folder path is given this way?

### ISSUE THREAD

**Issue by phonty29** [datalens-tech/datalens-backend#443]
```
vars:
  DATALENS_UI_FOLDER: '{{.DATALENS_UI_FOLDER | default "../../../../datalens-ui"}}'
```

So it will be cloned in folder that one step upper than backend repository "../../datalens-backend".
Shouldn't be backend and UI in one folder ?

**Comment by ovsds** [comment]
Hello, you're right indeed, using proper relative path in its [workflow](https://github.com/datalens-tech/datalens-backend/blob/main/.github/workflows/run_e2e_on_ref_local.yml#L65).
Fixing default for local folder instead of outside the project  in [PR](https://github.com/datalens-tech/datalens-backend/pull/444).
